Update test-only-plugin.gitlab-ci.yml

diff --git a/jobs/test/test-only-plugin.gitlab-ci.yml b/jobs/test/test-only-plugin.gitlab-ci.yml
--- a/jobs/test/test-only-plugin.gitlab-ci.yml
+++ b/jobs/test/test-only-plugin.gitlab-ci.yml
@@ -18,46 +18,51 @@ prepare-test-only-plugin:
         - |
           $files = @();
           $files2 = @();
-          function GetDependencies() 
-          {
-              $csProjPath = "$CI_PROJECT_DIR/CI_PROJECT_NAME.csproj";
-              if(Test-Path -Path $csProjPath) 
-              {
-                  $correctReference = '<Reference Include=".*" HintPath="\$\(MISTAKEN_REFERENCES\)(\/|\\)(.*\.dll)" \/>'
 
-                  $correctMultiLineReference = '<HintPath>\$\(MISTAKEN_REFERENCES\)(\/|\\)(.*\.dll)<\/HintPath>'
-                  $content = Get-Content $csProjPath;
-                  for($i = 0; $i -lt $content.length; $i++) 
+          $csProjPath = "$CI_PROJECT_DIR\$CI_PROJECT_NAME.csproj";
+          if(Test-Path -Path $csProjPath) 
+          {
+              $correctReference = '<Reference Include=".*" HintPath="\$\(MISTAKEN_REFERENCES\)[\/\\](.*\.dll)" \/>'
+
+              $correctMultiLineReference = '<HintPath>\$\(MISTAKEN_REFERENCES\)(\/|\\)(.*\.dll)<\/HintPath>'
+              $content = Get-Content $csProjPath;
+              for($i = 0; $i -lt $content.length; $i++) 
+              {
+                  $line = $content[$i];
+
+                  if($line -match $correctReference)
                   {
-                      $line = $content[$i];
-                      if($line -match $correctReference)
-                      {
-                          $files += [regex]::match($raw, $correctReference).Groups[2].Value;
-                      }
-                      elseif($line -match $correctMultiLineReference)
-                      {
-                          $files += [regex]::match($raw, $correctMultiLineReference).Groups[2].Value;
-                      }
+                      $files += [regex]::match($line, $correctReference).Groups[1].Value;
+                  }
+                  elseif($line -match $correctMultiLineReference)
+                  {
+                      $files += [regex]::match($line, $correctMultiLineReference).Groups[1].Value;
                   }
               }
-              else 
-              {
-                  echo "Project file not found as $csProjPath";
-                  exit 1;
-              }
+          }
+          else 
+          {
+              echo "Project file not found as $csProjPath";
+              exit 1;
           }
 
           foreach($file in $files) 
           {
-              if(($file -match "0Mistaken.API") -or ($file -match "Mistaken.Updater") -or ($file -match "Mistaken.RoundLogger") -or ($file -match "Mistaken.CITester"))
+              if(($file -match "0Mistaken\.API") -or ($file -match "Mistaken\.Updater") -or ($file -match "Mistaken\.RoundLogger") -or ($file -match "Mistaken\.CITester"))
               {
                   continue;
               }
+              if(($file -match "UnityEngine\.") -or ($file -match "Exiled\.") -or ($file -match "Mirror\.dll") -or ($file -match "CommandSystem\.Core\.dll") -or ($file -match "NorthwoodLib\.dll") -or ($file -match "Assembly"))
+              {
+                  continue;
+              }
+                
               $files2 += $file;
           }
 
           $tmp = $files2 -join ';';
           Add-Content -Path build.env -Value "REQUIED_PLUGINS=${tmp}"
+
 
 test-only-plugin:
     stage: test
